global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:

  # Monitorar o pr√≥prio Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Monitorar containers Docker (via exporter)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Monitorar MySQL (WordPress database)
  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]
